# Generated by Django 3.1.1 on 2020-09-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
    ]
